.TH "cuebreakpoints" "1"
.SH NAME
cuebreakpoints \- report track breakpoints from a CUE or TOC file
.SH SYNOPSIS
.B cuebreakpoints
[ {
.B \-i
.I format
|
.BR \-\-input\-format =\fIformat\fP
} {
.B \-\-append\-gaps
|
.B \-\-prepend\-gaps
|
.B \-\-split\-gaps
} ]
[
.I file
\&... ]
.br
.B cuebreakpoints \-h | \-\-help
.br
.B cuebreakpoints \-V | \-\-version
.SH DESCRIPTION
.B cuebreakpoints
reports the track breakpoints found in CUE and TOC files, which are
typically created by compact disc ripping software.
The breakpoints are in a format usable by
.B shnsplit
(part of the shntool package).
.PP
Three approaches to track pregaps are available: append (to previous track),
prepend (to succeeding track), and split (from both preceding and
succeeding tracks).
The split approach can result in up to twice as many breakpoints being
reported as there are tracks on the disc.
.PP
The first track's pregap cannot be appended to the previous track, so it is
prefixed to the track in both append and prepend modes.
If you want the track without it, use the
.B \-\-split\-gaps
option.
.PP
If no filenames are specified,
.B cuebreakpoints
reads from standard input, and an input format option
.I must
be specified.
If one or more filenames is provided, but the input format option is not
specified, the input format will be guessed based on each file's suffix
(e.g.,
.I .cue
or
.IR .toc ).
This heuristic is case-insensitive.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
displays a usage message and exits.
.TP
.BR \-i " \fIformat\fP, " \-\-input\-format=\fIformat\fP
sets the expected format of the input file(s) to
.IR format ,
which must be either
.B cue
or
.BR toc .
.TP
.B \-\-append\-gaps
appends pregaps to the end of the previous track.
This is the default.
.TP
.B \-\-prepend\-gaps
prefixes pregaps to the beginning of each subsequent track.
.TP
.B \-\-split\-gaps
separates pregaps from both the preceding and succeeding tracks.
.TP
.B \-V, \-\-version
displays version information and exits.
.PP
If more than one of
.BR \-\-append\-gaps ,
.BR \-\-prepend\-gaps ,
and
.B \-\-split\-gaps
are specified, all except the last encountered are ignored.
.SH "EXIT STATUS"
.B cuebreakpoints
exits with status zero if it successfully generates a report for each
input file, and nonzero if there were problems.
.SH AUTHOR
Cuetools was written by Svend Sorensen.
Branden Robinson contributed fixes and enhancements to the utilities and
documentation.
.SH "SEE ALSO"
.BR cueconvert (1),
.BR cueprint (1)
