.TH "CUETAG" "1"
.SH "NAME"
cuetag \- tag files based on cue/toc file information
.SH "SYNOPSIS"
.PP
cuetag <cuefile|tocfile> [file]...
.SH "DESCRIPTION"
This manual page documents briefly the
\fBcuetag\fR shell script.
.SH "AUTHOR"
This manual page was written by Patrick Matth\[:a]i <patrick.matthaei@web.de>
for cuetools.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 2 or any
later version published by the Free Software Foundation.
